pkg install python
pkg install python2
pkg install git
pkg install python-pip
pip install os
pip install datetime
pip install time
pip install threading
pip install psutil
pip install platform
pip install vk-api